# Generated by Django 5.1.6 on 2025-02-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='anonymous', max_length=100)),
                ('post_type', models.CharField(choices=[('simple', 'Simple'), ('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('caption', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('deleted', 'Deleted')], default='created', max_length=10)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
